/// Flutter icons Alcancia
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Alcancia
///      fonts:
///       - asset: fonts/Alcancia.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class Alcancia {
  Alcancia._();

  static const _kFontFam = 'Alcancia';
  static const _kFontPkg = null;

  static const IconData dot_menu = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
